# Adoption of: https://github.com/alaltitov/Waveshare-ESP32-P4-86-Panel-ETH-2RO

packages:
  main: !include WS-P4-Box/pages/main.yaml
  audio: !include WS-P4-Box/services/audio.yaml

esphome:
  name: waveshare-p4-box
  friendly_name: WaveShare P4 Box
  name_add_mac_suffix: false

# external_components:
#   - source: github://clydebarrow/esphome@mipi-dsi
#     components: [mipi, mipi_dsi, const, esp_ldo]

esp32:
  board: esp32-p4-evboard
  flash_size: 32Mb
  cpu_frequency: 400MHz
  framework:
    type: esp-idf
    platform_version: https://github.com/pioarduino/platform=espressif32/releases/download/54.03.21/platform-espressif32.zip
    # version: 5.4.2
    # platform_version: 54.03.21
    advanced:
      enable_idf_experimental_features: yes

logger:
  level: debug
  logs:
    lvgl: info
  hardware_uart: UART0

# debug:

psram:
  speed: 200MHz

esp_ldo:
  - channel: 3
    voltage: 2.5V

# ethernet:
#   type: IP101
#   mdc_pin: GPIO31
#   mdio_pin: GPIO52
#   clk: 
#     pin: GPIO50
#     mode: CLK_EXT_IN
#   phy_addr: 1
#   power_pin: GPIO51

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

display:
  - platform: mipi_dsi
    model: WAVESHARE-P4-86-PANEL

i2c:
  sda: GPIO7
  scl: GPIO8
  scan: true
  frequency: 400kHz
  id: i2c_bus

touchscreen:
  - platform: gt911
    id: touchscreen_
    # address: 0x14
    on_touch:
      - logger.log:
          format: "Touch at %d/%d"
          args: [touch.x, touch.y]

output:
  - platform: ledc
    id: backlight_
    pin: GPIO26
    frequency: 100Hz
    inverted: true
    min_power: 0.1 # To prevent the backlight from being too dim
    max_power: 0.8 # 0.8 To prevent overheating due to excessive lighting
    
light:
  - platform: monochromatic
    name: "backlight"
    output: backlight_
    id: backlight_light
    restore_mode: ALWAYS_ON

api:
  # encryption:
  #   key: !secret waveshare_api

ota:
  - platform: esphome
  #   password: !secret waveshare_ota

lvgl:
  buffer_size: 100%
  byte_order: little_endian


